"""add_stage_and_progress_to_ingestion_jobs

Revision ID: 0c055b1c7da5
Revises: efe2d2f697b3
Create Date: 2026-09-30 17:17:25.540223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c055b1c7da5'
down_revision: Union[str, Sequence[str], None] = 'efe2d2f697b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('stage', sa.String(length=32), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'progress')
    op.drop_column('ingestion_jobs', 'stage')
    # ### end Alembic commands ###
